PrisonBreak:
  BlackMarkets:
    Schematic: BlackMarket
    Locations:
      Location-1:
        Location: 1284.5;4;372.5
        Rotation: 0
      Location-2:
        Location: 1210.5;4;442.5
        Rotation: 90
      Location-3:
        Location: 1058.5;4;525.5
        Rotation: 0
      Location-4:
        Location: 1156.5;4.5;622.5
        Rotation: 270
    NPCS:
      NPC-1:
        Name: Vendor
        Location: 983.5;10;459.5
      NPC-2:
        Name: Vendor
        Location: 983.5;10;471.5
    Holograms:
      Lobby:
        Message: Teleport to Lobby
        Location: 977.5;10.5;465.5
      Kicked:
        Message: Disconnect from Server
        Location: 989.5;10.5;465.5
    Sell-Boosters:
      1:
        Permission: prisonbreak.sellbooster.1
        Percentage: 10