PrisonBreak:
  Kits:
    Example-Kit:
        Permission: prisonbreak.kits.example-kit
        Items:
          DIAMOND_SWORD: 1
          DIAMOND_AXE: 1
          DIAMOND_PICKAXE: 1
          DIAMOND_SPADE: 1
          DIAMOND_BOOTS: 1
          DIAMOND_LEGGINGS: 1
          DIAMOND_CHESTPLATE: 1
          DIAMOND_HELMET: 1
          BREAD: 16
          APPLE: 16
    Gold:
        Permission: prisonbreak.kits.gold
        Items:
          DIAMOND_SWORD: 1
          DIAMOND_AXE: 1
          DIAMOND_PICKAXE: 1
          DIAMOND_SPADE: 1
          DIAMOND_BOOTS: 1
          DIAMOND_LEGGINGS: 1
          DIAMOND_CHESTPLATE: 1
          DIAMOND_HELMET: 1
          BREAD: 16
          APPLE: 16
    Diamond:
        Permission: prisonbreak.kits.diamond
        Items:
          DIAMOND_SWORD: 1
          DIAMOND_AXE: 1
          DIAMOND_PICKAXE: 1
          DIAMOND_SPADE: 1
          DIAMOND_BOOTS: 1
          DIAMOND_LEGGINGS: 1
          DIAMOND_CHESTPLATE: 1
          DIAMOND_HELMET: 1
          BREAD: 16
          APPLE: 16
    Bedrock:
        Permission: prisonbreak.kits.bedrock
        Items:
          DIAMOND_SWORD: 1
          DIAMOND_AXE: 1
          DIAMOND_PICKAXE: 1
          DIAMOND_SPADE: 1
          DIAMOND_BOOTS: 1
          DIAMOND_LEGGINGS: 1
          DIAMOND_CHESTPLATE: 1
          DIAMOND_HELMET: 1
          BREAD: 16
          APPLE: 16

